### ISSUE TITLE
Issue Comment

### ISSUE THREAD

**Issue by Daniel-Sanborn** [Daniel-Sanborn/markdown-portfolio#2]
### Tasks ###
- [x] Practice markdown formatting: **bold**, *italic*, <del>strikethrough</del>, et cetera
- [ ] Optionally, review [Quick Reference Guide] (https://lab.github.com/public/communicating-using-markdown.pdf)
- [ ] Optionally, review ["Writing On GitHub"] (https://help.github.com/categories/writing-on-github/)

**Comment by Daniel-Sanborn** [comment]
The **GitPages** function was activated under the *main* branch; the 'Theme' settings weren't modified.

**Comment by Daniel-Sanborn** [comment]
Determine the next step?
